// TODO(seed-data): the real Airsafe MAR workbook (row descriptions, TOR article
// numbers, actual tick states) was not available when this seed was written.
// Every field marked "[TODO(seed-data): ...]" below is a structurally-correct
// placeholder — the group/priority/row/column/check COUNTS are exact per
// CLAUDE.md §5.4 (28 items, 14 detail sheets, 282 checks total), but text
// content and tick state must be replaced with the verbatim workbook data.
// Do not touch domain/derive.ts or components when swapping this content in.
import type { CheckColumn, CheckRow, DetailSheet, GroupId, Item, Priority } from './types'

const ROW_REMARK = 'Rev.0 - 20260725'

function groupFor(no: number): GroupId {
  if (no <= 8) return 'G1'
  if (no <= 12) return 'G2'
  if (no <= 21) return 'G3'
  if (no <= 27) return 'G4'
  return 'G5'
}

function priorityFor(no: number): Priority {
  if (no === 28 || no <= 10) return 'A'
  if (no <= 24) return 'B'
  return 'C'
}

const TODO_TEXT = '[TODO(seed-data): verbatim workbook text pending]'

interface ItemOverride {
  name: string
  standard?: string
  hasSheet?: boolean
}

// Fields given verbatim in CLAUDE.md §5.2/§5.4/§2.2 — not fabricated.
const ITEM_OVERRIDES: Record<number, ItemOverride> = {
  1: {
    name: 'Technical Datasheet / Product Catalogs',
    standard: 'Clause 1.4.O / ICAO Annex 14 / IEC TS 61827 / FAA AC 150/5345-46E',
    hasSheet: true,
  },
  2: { name: 'Third-Party Certificates', hasSheet: true },
  3: {
    name: 'FAA ALECP Listing (AC 150/5345-53 Addendum)',
    standard: 'FAA AC 150/5345-53 Addendum — ALECP',
    hasSheet: true,
  },
  4: { name: 'Complete LM-79 Test Reports', standard: 'IES LM-79', hasSheet: true },
  5: {
    name: 'LM-80 Test Reports & TM-21 Evaluation Reports',
    standard: 'IES LM-80 / TM-21',
    hasSheet: true,
  },
  6: {
    name: 'Dimming Curve Data per FAA EB-67',
    standard: 'FAA Engineering Brief (EB) 67',
    hasSheet: true,
  },
  7: { name: 'Corrosion Test Report', hasSheet: true },
  9: { name: 'Isolation Transformer', hasSheet: true },
  10: { name: 'RCMU / SLC (Lamp Control Unit)', hasSheet: true },
  11: { name: 'Fixture Base, Connector Kits & Accessories', hasSheet: true },
  12: { name: 'CCR-I Test Reports for Missing Sizes / Ratings', hasSheet: true },
  25: { name: 'Project References & Letter of Acceptance', hasSheet: true },
  26: { name: 'Appointment Letter — Distributor / Service Provider', hasSheet: true },
  27: { name: 'O&M Manuals & Training Program', hasSheet: true },
  28: { name: 'MAR Submission Letter (Contractor Cover Letter)' },
}

export const items: Item[] = Array.from({ length: 28 }, (_, i) => {
  const no = i + 1
  const override = ITEM_OVERRIDES[no]
  const item: Item = {
    no,
    group: groupFor(no),
    name: override?.name ?? `Item ${no} — ${TODO_TEXT}`,
    standard: override?.standard ?? TODO_TEXT,
    requirement: TODO_TEXT,
    priority: priorityFor(no),
  }
  if (override?.hasSheet) item.detailSheetId = `item-${no}`
  // Item 3's remark is generated by domain/derive.ts (§6.5) — never stored here.
  return item
})

function uniformRows(count: number, columns: CheckColumn[], idPrefix: string): CheckRow[] {
  return Array.from({ length: count }, (_, i) => {
    const n = i + 1
    return {
      id: `${idPrefix}-row-${n}`,
      description: `Row ${n} — ${TODO_TEXT}`,
      cells: Object.fromEntries(columns.map((c) => [c.key, false])),
      remark: ROW_REMARK,
    }
  })
}

const item1Columns: CheckColumn[] = [
  { key: 'model', label: 'Model No. / Ordering Ref.' },
  { key: 'rating', label: 'Rating' },
  { key: 'dimension', label: 'Dimension' },
  { key: 'material', label: 'Material' },
  { key: 'photometric', label: 'Photometric Data' },
]

const item2Columns: CheckColumn[] = [{ key: 'thirdPartyCert', label: 'Third-Party Certificate' }]

const item3Columns: CheckColumn[] = [{ key: 'faaAlecp', label: 'FAA ALECP Listing' }]

const item4Columns: CheckColumn[] = [{ key: 'lm79', label: 'LM-79' }]

const item5Columns: CheckColumn[] = [
  { key: 'lm80', label: 'LM-80' },
  { key: 'tm21', label: 'TM-21' },
]

const item6Columns: CheckColumn[] = [{ key: 'dimmingCurve', label: 'Dimming Curve' }]

const item7Columns: CheckColumn[] = [{ key: 'corrosionReport', label: 'Corrosion Report' }]

const item9Columns: CheckColumn[] = [
  { key: 'datasheet', label: 'Datasheet' },
  { key: 'testCert', label: 'Test Cert' },
  { key: 'typeTest', label: 'Type Test' },
]

const item10Columns: CheckColumn[] = [
  { key: 'techSpec', label: 'Tech Spec' },
  { key: 'plcProtocol', label: 'PLC Protocol' },
  { key: 'typeTest', label: 'Type Test' },
  { key: 'evidence', label: 'Evidence' },
]

const specTestCertColumns: CheckColumn[] = [
  { key: 'specification', label: 'Specification' },
  { key: 'referenceStdTestCert', label: 'Reference Std / Test Cert' },
]

const item25Columns: CheckColumn[] = [
  { key: 'projectRefs', label: 'Project Refs' },
  { key: 'letterOfAcceptance', label: 'Letter of Acceptance' },
]

const item26Columns: CheckColumn[] = [
  { key: 'authorizedDistributor', label: 'Authorized Distributor' },
  { key: 'serviceProvider', label: 'Service Provider' },
]

const item27Columns: CheckColumn[] = [
  { key: 'oAndMManuals', label: 'O&M Manuals' },
  { key: 'trainingProgram', label: 'Training Program' },
]

function buildItem2Rows(): CheckRow[] {
  const rows = uniformRows(19, item2Columns, 'item-2')
  rows.push({
    id: 'item-2-row-20',
    description: 'Summary Table',
    cells: { thirdPartyCert: false },
    remark: ROW_REMARK,
    section: 'Summary',
  })
  return rows
}

export const detailSheets: DetailSheet[] = [
  {
    id: 'item-1',
    itemNo: 1,
    title: 'Technical Datasheet / Product Catalogs',
    applicable: 'Clause 1.4.O / ICAO Annex 14 / IEC TS 61827 / FAA AC 150/5345-46E',
    columns: item1Columns,
    rows: uniformRows(19, item1Columns, 'item-1'),
  },
  {
    id: 'item-2',
    itemNo: 2,
    title: 'Third-Party Certificates',
    applicable: TODO_TEXT,
    columns: item2Columns,
    rows: buildItem2Rows(),
  },
  {
    id: 'item-3',
    itemNo: 3,
    title: 'FAA ALECP Listing (AC 150/5345-53 Addendum)',
    applicable: 'FAA AC 150/5345-53 Addendum — ALECP',
    columns: item3Columns,
    rows: uniformRows(25, item3Columns, 'item-3'),
  },
  {
    id: 'item-4',
    itemNo: 4,
    title: 'Complete LM-79 Test Reports',
    applicable: 'IES LM-79',
    columns: item4Columns,
    rows: uniformRows(19, item4Columns, 'item-4'),
  },
  {
    id: 'item-5',
    itemNo: 5,
    title: 'LM-80 Test Reports & TM-21 Evaluation Reports',
    applicable: 'IES LM-80 / TM-21',
    columns: item5Columns,
    rows: uniformRows(19, item5Columns, 'item-5'),
  },
  {
    id: 'item-6',
    itemNo: 6,
    title: 'Dimming Curve Data per FAA EB-67',
    applicable: 'FAA Engineering Brief (EB) 67',
    columns: item6Columns,
    rows: uniformRows(19, item6Columns, 'item-6'),
  },
  {
    id: 'item-7',
    itemNo: 7,
    title: 'Corrosion Test Report',
    applicable: TODO_TEXT,
    columns: item7Columns,
    rows: uniformRows(19, item7Columns, 'item-7'),
  },
  {
    id: 'item-9',
    itemNo: 9,
    title: 'Isolation Transformer',
    applicable: TODO_TEXT,
    columns: item9Columns,
    rows: uniformRows(1, item9Columns, 'item-9'),
  },
  {
    id: 'item-10',
    itemNo: 10,
    title: 'RCMU / SLC (Lamp Control Unit)',
    applicable: TODO_TEXT,
    columns: item10Columns,
    rows: uniformRows(1, item10Columns, 'item-10'),
  },
  {
    id: 'item-11',
    itemNo: 11,
    title: 'Fixture Base, Connector Kits & Accessories',
    applicable: TODO_TEXT,
    columns: specTestCertColumns,
    rows: uniformRows(8, specTestCertColumns, 'item-11'),
  },
  {
    id: 'item-12',
    itemNo: 12,
    title: 'CCR-I Test Reports for Missing Sizes / Ratings',
    applicable: TODO_TEXT,
    columns: specTestCertColumns,
    rows: uniformRows(9, specTestCertColumns, 'item-12'),
  },
  {
    id: 'item-25',
    itemNo: 25,
    title: 'Project References & Letter of Acceptance',
    applicable: TODO_TEXT,
    columns: item25Columns,
    rows: uniformRows(1, item25Columns, 'item-25'),
  },
  {
    id: 'item-26',
    itemNo: 26,
    title: 'Appointment Letter — Distributor / Service Provider',
    applicable: TODO_TEXT,
    columns: item26Columns,
    rows: uniformRows(1, item26Columns, 'item-26'),
  },
  {
    id: 'item-27',
    itemNo: 27,
    title: 'O&M Manuals & Training Program',
    applicable: TODO_TEXT,
    columns: item27Columns,
    rows: uniformRows(1, item27Columns, 'item-27'),
  },
]

/**
 * PLACEHOLDER TICK PATTERN — real tick state from the workbook is unavailable,
 * so the first N cells in stable sheet/row/column order are ticked, giving an
 * exact, reproducible 120/282 (~43%) rather than an invented "realistic" spread.
 * Replace with real workbook state once available.
 */
function applyDeterministicTicks(sheets: DetailSheet[], totalToTick: number): void {
  let remaining = totalToTick
  for (const sheet of sheets) {
    for (const row of sheet.rows) {
      for (const key of Object.keys(row.cells)) {
        if (remaining <= 0) return
        row.cells[key] = true
        remaining -= 1
      }
    }
  }
}

applyDeterministicTicks(detailSheets, 120)
